
version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - state_data:/data
    environment:
      - PYTHONUNBUFFERED=1
  dev:
    image: python:3.11-slim
    working_dir: /srv
    volumes:
      - .:/srv
      - state_data:/data
    ports:
      - "8000:8000"
    command: bash -lc "pip install fastapi uvicorn pydantic[dotenv] && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
volumes:
  state_data:
